- name: Pull from github repository
  git:
    repo: https://github.com/seser1/docker-compose-files.git
    dest: "{{ pull_git_working_directory }}/docker-files"
    force: true

- name: Copy ssl key to server
  copy:
    src: ssl
    dest: "{{ pull_git_working_directory }}/docker-files/server-repos/data/nginx"

- name: Copy gogs settings to server
  copy:
    src: gogs/app.ini
    dest: "{{ pull_git_working_directory }}/docker-files/server-repos/data/gogs/gogs/conf/app.ini"

- name: Run docker-compose
  shell: |
    cd "{{ pull_git_working_directory }}/docker-files/server-repos"
    docker-compose up -d
